[package]
name = "task1"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.4.0"
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
dotenv = "0.15"
